name = "insurance-adjuster-ai"
compatibility_date = "2024-01-01"

[env.production]
  Workers = true
  Functions = ["src/functions/**/*.js"]

[env.development]
  workers_dev = true

[vars.production]
  VITE_OPENAI_KEY = ""

[vars.development]
  VITE_OPENAI_KEY = ""
